import { tokens } from "./tokens";
import { tokenKeyToCssVar, sidebarKeyToCssVar } from "./utils";
import * as fs from "fs";
import * as path from "path";

function hexToHsl(hex: string): string {
  const r = parseInt(hex.slice(1, 3), 16) / 255;
  const g = parseInt(hex.slice(3, 5), 16) / 255;
  const b = parseInt(hex.slice(5, 7), 16) / 255;

  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const l = (max + min) / 2;

  if (max === min) return `${0} 0% ${Math.round(l * 100)}%`;

  const d = max - min;
  const s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
  let h = 0;

  if (max === r) h = ((g - b) / d + (g < b ? 6 : 0)) / 6;
  else if (max === g) h = ((b - r) / d + 2) / 6;
  else h = ((r - g) / d + 4) / 6;

  return `${Math.round(h * 360)} ${Math.round(s * 100)}% ${Math.round(l * 100)}%`;
}

function generateCssVariables(): string {
  const lines: string[] = [];

  lines.push("  /* Generated by design-system/generate-css.ts — do not edit manually */");

  for (const [key, value] of Object.entries(tokens.colors)) {
    lines.push(`  ${tokenKeyToCssVar(key)}: ${hexToHsl(value)};`);
  }

  lines.push("");
  for (const [key, value] of Object.entries(tokens.sidebar)) {
    lines.push(`  ${sidebarKeyToCssVar(key)}: ${hexToHsl(value)};`);
  }

  lines.push("");
  lines.push(`  --radius: ${tokens.radius};`);

  return lines.join("\n");
}

const cssVars = generateCssVariables();

const globalsPath = path.resolve(__dirname, "../app/globals.css");
let content = fs.readFileSync(globalsPath, "utf-8");

const marker = "/* DESIGN_TOKENS_START */";
const markerEnd = "/* DESIGN_TOKENS_END */";

if (content.includes(marker)) {
  const startIdx = content.indexOf(marker);
  const endIdx = content.indexOf(markerEnd) + markerEnd.length;
  content = content.slice(0, startIdx) + `${marker}\n${cssVars}\n  ${markerEnd}` + content.slice(endIdx);
} else {
  const darkIdx = content.indexOf("@theme inline {");
  if (darkIdx !== -1) {
    const insertIdx = content.indexOf("{", darkIdx) + 1;
    content = content.slice(0, insertIdx) + `\n  ${marker}\n${cssVars}\n  ${markerEnd}\n` + content.slice(insertIdx);
  }
}

fs.writeFileSync(globalsPath, content);
console.log("Design tokens generated successfully.");
