export const tokens = {
  colors: {
    primary: "#17171c",
    primaryForeground: "#ffffff",
    background: "#0c0c11",
    foreground: "#ededf0",
    card: "#151519",
    cardForeground: "#ededf0",
    popover: "#151519",
    popoverForeground: "#ededf0",
    secondary: "#1e1e24",
    secondaryForeground: "#c8c8d0",
    muted: "#1a1a20",
    mutedForeground: "#93939f",
    accent: "#ff7759",
    accentForeground: "#ffffff",
    destructive: "#b30000",
    destructiveForeground: "#ffffff",
    border: "#28282f",
    input: "#28282f",
    ring: "#ff7759",
    chart1: "#ff7759",
    chart2: "#ffad9b",
    chart3: "#4c6ee6",
    chart4: "#1863dc",
    chart5: "#003c33",
  },
  sidebar: {
    background: "#0a0a0f",
    foreground: "#c8c8d0",
    primary: "#ff7759",
    primaryForeground: "#ffffff",
    accent: "#1a1a20",
    accentForeground: "#ededf0",
    border: "#28282f",
    ring: "#ff7759",
  },
  spacing: {
    xxs: "0.125rem",
    xs: "0.375rem",
    sm: "0.5rem",
    md: "0.75rem",
    lg: "1rem",
    xl: "1.5rem",
    "2xl": "2rem",
    "3xl": "3rem",
    section: "5rem",
  },
  typography: {
    fontDisplay: "var(--font-display), 'Space Grotesk', 'Inter', system-ui, sans-serif",
    fontSans: "var(--font-sans), 'Inter', system-ui, sans-serif",
    fontMono: "var(--font-mono), 'JetBrains Mono', monospace",
    sizes: {
      micro: "0.75rem",
      caption: "0.875rem",
      body: "1rem",
      bodyLarge: "1.125rem",
      featureHeading: "1.5rem",
      cardHeading: "2rem",
      sectionHeading: "3rem",
      display: "4.5rem",
    },
  },
  radius: "0.5rem",
  rounded: {
    xs: "0.25rem",
    sm: "0.5rem",
    md: "1rem",
    lg: "1.375rem",
    xl: "1.875rem",
    pill: "9999px",
  },
} as const;

export type Tokens = typeof tokens;
