export const tokens = {
  colors: {
    primary: "#1A3A18",
    primaryForeground: "#ffffff",
    background: "#050806",
    foreground: "#e8f0e8",
    card: "#0c1a0e",
    cardForeground: "#e8f0e8",
    popover: "#0c1a0e",
    popoverForeground: "#e8f0e8",
    secondary: "#1a2e1a",
    secondaryForeground: "#c8dcc8",
    muted: "#142214",
    mutedForeground: "#8aaa8a",
    accent: "#4CAF50",
    accentForeground: "#ffffff",
    destructive: "#dc2626",
    destructiveForeground: "#ffffff",
    border: "#1e3a1e",
    input: "#1e3a1e",
    ring: "#4CAF50",
    chart1: "#4CAF50",
    chart2: "#66BB6A",
    chart3: "#81C784",
    chart4: "#A5D6A7",
    chart5: "#C8E6C9",
  },
  sidebar: {
    background: "#070d08",
    foreground: "#c8dcc8",
    primary: "#4CAF50",
    primaryForeground: "#ffffff",
    accent: "#142214",
    accentForeground: "#e8f0e8",
    border: "#1e3a1e",
    ring: "#4CAF50",
  },
  spacing: {
    xs: "0.25rem",
    sm: "0.5rem",
    md: "1rem",
    lg: "1.5rem",
    xl: "2rem",
    "2xl": "3rem",
    "3xl": "4rem",
  },
  typography: {
    fontFamily: "var(--font-geist-sans), system-ui, sans-serif",
    fontMono: "var(--font-geist-mono), monospace",
    sizes: {
      xs: "0.75rem",
      sm: "0.875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": "2.25rem",
      "5xl": "3rem",
    },
  },
  radius: "0.625rem",
} as const;

export type Tokens = typeof tokens;
